<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('employees', function (Blueprint $table) {
            // Drop the existing FK (generated by `foreignId()->constrained()`)
            $table->dropForeign(['dept_id']);

            // Re-create it with cascade delete
            $table->foreign('dept_id')
                ->references('dept_id')
                ->on('departments')
                ->onDelete('cascade');
        });
    }

    public function down(): void
    {
        Schema::table('employees', function (Blueprint $table) {
            $table->dropForeign(['dept_id']);

            // Revert to default MySQL behavior (NO ACTION)
            $table->foreign('dept_id')
                ->references('dept_id')
                ->on('departments');
        });
    }
};

